from django import forms

class CadastroClienteForm(forms.Form):
    nome        = forms.CharField(label='Nome', max_length=200)
    cpf         = forms.CharField(label='CPF/CNPJ', max_length=16)
    endereco    = forms.CharField(label='Endereço', max_length=256)
    bairro      = forms.CharField(label='Bairro', max_length=128)
    cidade      = forms.CharField(label='Cidade', max_length=128)
    cep         = forms.CharField(label='CEP', max_length=16)
    uf          = forms.CharField(label='UF', max_length=2)
    telefone1   = forms.CharField(label='Telefone 1', max_length=32)
    telefone2   = forms.CharField(label='Telefone 2', max_length=32, required=False)
    telefone3   = forms.CharField(label='Telefone 3', max_length=32, required=False)
    telefone4   = forms.CharField(label='Telefone 4', max_length=32, required=False)
    telefone5   = forms.CharField(label='Telefone 5', max_length=32, required=False)
    telefone6   = forms.CharField(label='Telefone 6', max_length=32, required=False)
    email1      = forms.EmailField(label='Email 1', max_length=200, required=False)
    email2      = forms.EmailField(label='Email 2', max_length=200, required=False)
    email3      = forms.EmailField(label='Email 3', max_length=200, required=False)
    email4      = forms.EmailField(label='Email 4', max_length=200, required=False)
    email5      = forms.EmailField(label='Email 5', max_length=200, required=False)
    email6      = forms.EmailField(label='Email 6', max_length=200, required=False)
    numop       = forms.IntegerField(label='Número da Operação')
    nomeop      = forms.CharField(label='Nome da Operação', max_length=255, required=False)
    vencimento  = forms.DateTimeField(label='Vencimento', required=False)
    valorop     = forms.FloatField(label='Valor Nominal', required=False)
    nomealuno   = forms.CharField(label='Nome do Aluno', max_length=255, required=False)
    descricao   = forms.CharField(label='Descrição (Ano/Série)', max_length=255, required=False)
    