# Generated by Django 3.2.3 on 2021-05-31 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpfcnpj', models.CharField(max_length=16)),
                ('endereco', models.CharField(max_length=256, null=True)),
                ('bairro', models.CharField(max_length=128, null=True)),
                ('cidade', models.CharField(max_length=128, null=True)),
                ('cep', models.CharField(max_length=16, null=True)),
                ('uf', models.CharField(max_length=2, null=True)),
                ('telefone1', models.CharField(max_length=32, null=True)),
                ('telefone2', models.CharField(max_length=32, null=True)),
                ('telefone3', models.CharField(max_length=32, null=True)),
                ('telefone4', models.CharField(max_length=32, null=True)),
                ('telefone5', models.CharField(max_length=32, null=True)),
                ('telefone6', models.CharField(max_length=32, null=True)),
                ('email1', models.CharField(max_length=200, null=True)),
                ('email2', models.CharField(max_length=200, null=True)),
                ('email3', models.CharField(max_length=200, null=True)),
                ('email4', models.CharField(max_length=200, null=True)),
                ('email5', models.CharField(max_length=200, null=True)),
                ('email6', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Credor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_op', models.IntegerField()),
                ('nome_op', models.CharField(max_length=255, null=True)),
                ('vencimento', models.DateTimeField(null=True)),
                ('nome_aluno', models.CharField(max_length=255, null=True)),
                ('descricao', models.CharField(max_length=255, null=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.cliente')),
                ('id_credor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.credor')),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('tipoemail', models.IntegerField()),
                ('diasvenc', models.IntegerField()),
                ('horadisparo', models.TimeField()),
                ('mensagem', models.TextField()),
                ('id_credor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.credor')),
            ],
        ),
    ]
